version: '3'
services:
  nifi: 
    image: 'apache/nifi:1.18.0'
    hostname: 'nifi-demo'
    ports:
      - '8443:8443' # nifi ui 
      - '9005:9005' # http listener by nifi
    volumes: 
      - "./nifi/logs:/opt/nifi/nifi-current/logs"
      - "./nifi/keystore:/opt/nifi/nifi-current/keystore"
      - "./data:/opt/nifi/data"